spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: false
    gateway:
      discovery:
        locator:
          filters:
            - name: StripPrefix
              args:
                parts: 1



logging:
  level:
    org.springframework.cloud.gateway: DEBUG