spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: false
    gateway:
      discovery:
        locator:
          filters:
            - name: StripPrefix
              args:
                parts: 1