server:
  port: 50011

spring:
  elasticsearch:
    uris: http://linux-082:50005
    username: elastic
    password: '{vault}:product/product-search-service#PRODUCT_ELASTICSEARCH_SERVICE_PASSWORD'
    connection-timeout: 2s
    socket-timeout: 5s