spring:
  data:
    mongodb:
      uri: '{vault}:product/product-database#PRODUCT_MONGODB_SERVICE_URI'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${service.uri.eureka}/eureka

firebase:
  apikey: "{vault:user-service/USER_FIREBASE_API_KEY}"


      

